// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChBFPOAet8CMQa9AkyOoPcCb6CGkwxBbY',
    appId: '1:25327566024:web:fc38032751f2216e3579fd',
    messagingSenderId: '25327566024',
    projectId: 'agro-smart-app',
    authDomain: 'agro-smart-app.firebaseapp.com',
    storageBucket: 'agro-smart-app.firebasestorage.app',
    measurementId: 'G-T57ZRS4XHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfyT9wwJZJ04rgiReviR3dZ5hRTfw0PKQ',
    appId: '1:25327566024:android:67682fc9ec77dead3579fd',
    messagingSenderId: '25327566024',
    projectId: 'agro-smart-app',
    storageBucket: 'agro-smart-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8KJ87vu2EK3jlafN0WghAXzvlDSCyJ0',
    appId: '1:25327566024:ios:0c3bb0b5d2a2d0da3579fd',
    messagingSenderId: '25327566024',
    projectId: 'agro-smart-app',
    storageBucket: 'agro-smart-app.firebasestorage.app',
    iosBundleId: 'com.example.cropRecommendationApp',
  );
}
